services:
  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - mongo_data:/data/db
    networks:
      - mcr_net

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    env_file:
      - ../.env
    volumes:
      - ../backend:/app
      - /app/node_modules
    networks:
      - mcr_net
    depends_on:
      - mongo

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile.dev
    container_name: gateway_dev
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    env_file:
      - ../.env
    volumes:
      - ../gateway:/app
      - /app/node_modules
    networks:
      - mcr_net
    depends_on:
      - backend

volumes:
  mongo_data:

networks:
  mcr_net:
    driver: bridge